import type { Metadata } from "next";
import "./globals.css";
import { ThemeWrapper } from './theme/ThemeContext';
import { Toaster } from 'react-hot-toast';
import { poppins } from './theme/fonts';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.className}>
      <body>
        <ThemeWrapper>
          {children}
          <Toaster position="top-right" toastOptions={{
            duration: 4000,
            style: {
              background: '#333',
              color: '#fff',
            },
            success: {
              iconTheme: {
                primary: '#22c55e',
                secondary: '#fff',
              },
            },
            error: {
              iconTheme: {
                primary: '#ef4444',
                secondary: '#fff',
              },
            },
          }} />
        </ThemeWrapper>
      </body>
    </html>
  );
}
