import type { Metadata } from "next";
import "./globals.css";
import { ThemeWrapper } from '@/context/ThemeContext';
import { Toaster } from 'react-hot-toast';
import { poppins } from './theme/fonts';
import { CartProvider } from '../context/CartContext';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.className}>
      <body>
        <ThemeWrapper>
          <CartProvider>
            {children}
            <Toaster position="top-right" toastOptions={{
              duration: 4000,
              style: {
                background: '#333',
                color: '#fff',
              },
              success: {
                iconTheme: {
                  primary: '#22c55e',
                  secondary: '#fff',
                },
              },
              error: {
                iconTheme: {
                  primary: '#ef4444',
                  secondary: '#fff',
                },
              },
            }} />
          </CartProvider>
        </ThemeWrapper>
      </body>
    </html>
  );
}
